mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vocaapp.urls'))
]

vocaapp/urls.py
from django.urls import path
from . import views

app_name = 'vocaapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), 
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
]

vocaapp/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """問題カテゴリ"""
    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        """テキストの値を返す"""
        return self.name


class Post(models.Model):
    """問題本文と答え"""
    question = models.TextField('問題文')
    answer = models.TextField('答え')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)

    def __str__(self):
        """テキストの値を返す"""
        return self.question

vocaapp/views.py
from django.shortcuts import render

# # Create your views here.
from django.views import generic
from .models import Post, Category


class IndexView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.order_by('-created_at')


class CategoryView(generic.ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        """
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('created_at').filter(category=category)
        """
        category_pk = self.kwargs['pk']
        queryset = Post.objects.order_by('-created_at').filter(category__pk=category_pk)
        return queryset


class DetailView(generic.DetailView):
    model = Post

vocaapp/templates/vocaapp/base.html
<!doctype html>
<html lang="ja" xmlns:display="http://www.w3.org/1999/xhtml">
  <head>
    <title>単語帳</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'vocaapp:index' %}" >VOCABULARY BOOK</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active" >
        <a class="nav-link" style="color: #00fa9a;">問題カテゴリ</a>
        {% for category in category_list %}
          <a class="nav-link" href="{% url 'vocaapp:category' category.pk %}" style="display: inline;">{{ category }}</a>
        {% endfor %}
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      {% endif %}
    </ul>
  </div>
　　</nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        {% block content %}
        {% endblock %}
      </div>
     </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

vocaapp/templates/vocaapp/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
  </ul>
</nav>

vocaapp/templates/vocaapp/post_detail.html
{% extends 'vocaapp/base.html' %}

{% block content %}
<div class="card mb-3 mt-4">
  <h4 class="card-header bg-dark text-white">{{ post.question }}</h4>
  <div class="card-body">
      <h3>{{ post.answer | linebreaksbr | urlize}}</h3>
      <br /><br />
      <form action="test06.cgi" method="post">
        <input type="submit" name="btn1" value="[1]" />
        <input type="submit" name="btn2" value="[2]" />
        <input type="submit" name="btn3" value="[3]" />
      </form>
      <a href="{{request.META.HTTP_REFERER}}" class="btn btn-dark">問題に戻る</a>
  </div>
</div>

{% endblock %}

vocaapp/templates/vocaapp/post_list.html
{% extends 'vocaapp/base.html' %}

{% block content %}
{% for post in post_list %}
<div class="card mb-4 mt-4">
  <h4 class="card-header bg-dark text-white">問題</h4>
  <div class="card-body">
      <h3>{{post.question}}</h3>
   <br /><br />
    <a href="{% url 'vocaapp:detail' post.pk %}" class="btn btn-dark">答えを見る</a>
  </div>
</div>
{% endfor %}

{% include 'vocaapp/page.html' %}

{% endblock %}